### ISSUE TITLE
Support for JSON output

### ISSUE THREAD

**Issue by NotoriousRebel** [edoardottt/csprecon#226]
Having JSON output as an option would be nice, especially when doing -l targets.txt, for example

```json
{"x.subdomain.com" : ["new.subdomain.com",  "second.subdomain.com", "etc.."]}
````

Just mapping the specific taarget to the domains found from CSP.

**Comment by edoardottt** [comment]
Hi @NotoriousRebel,

I'm trying to add support for JSON, but there is a weird behaviour appening.  
The devel branch (https://github.com/edoardottt/csprecon/tree/devel) contains the modifications applied to add support for JSON (see this commit https://github.com/edoardottt/csprecon/commit/3d731036582316a11d3594b569c7eba8cb9bfb4b).

The strange behaviour is surely caused by channels/concurrency/wait groups.

## Normal output (`-j` flag not specified)

The program processes all the input and exits normally.
Try with 
```console
echo URL | go run cmd/csprecon/csprecon.go
```
or 
```console
cat URLs.txt | go run cmd/csprecon/csprecon.go
```

## JSON output (`-j` flag specified)

The program processes all the input and doesn't exit, waits infinitely.
Try with 
```console
echo URL | go run cmd/csprecon/csprecon.go -j
```
or 
```console
cat URLs.txt | go run cmd/csprecon/csprecon.go -j
```

I don't know what I'm doing wrong here, let me know if ypu spot something.

**Comment by edoardottt** [comment]
Completed https://github.com/edoardottt/csprecon/commit/1afa44739a6a451f92703e3af5d303daf0fd154b
